"""Initial migration

Revision ID: 069e5a3a607e
Revises: 39ebf4006dd5
Create Date: 2024-06-06 23:33:50.805705

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '069e5a3a607e'
down_revision = '39ebf4006dd5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('utilisateur', schema=None) as batch_op:
        batch_op.add_column(sa.Column('motDePasse_hash', sa.String(length=200), nullable=False))
        batch_op.drop_column('motDePasse')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('utilisateur', schema=None) as batch_op:
        batch_op.add_column(sa.Column('motDePasse', mysql.VARCHAR(length=200), nullable=False))
        batch_op.drop_column('motDePasse_hash')

    # ### end Alembic commands ###
