"""empty message

Revision ID: a71e2b891876
Revises: bbca4061b560
Create Date: 2024-06-08 23:53:24.917112

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a71e2b891876'
down_revision = 'bbca4061b560'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admin', schema=None) as batch_op:
        batch_op.add_column(sa.Column('utilisateurId', sa.Integer(), nullable=False))
        batch_op.create_unique_constraint(None, ['utilisateurId'])
        batch_op.drop_constraint('admin_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'utilisateur', ['utilisateurId'], ['utilisateurId'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admin', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('admin_ibfk_1', 'utilisateur', ['adminId'], ['utilisateurId'])
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('utilisateurId')

    # ### end Alembic commands ###
