"""empty message

Revision ID: bbca4061b560
Revises: d4946cc6c566
Create Date: 2024-06-08 11:48:09.407706

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'bbca4061b560'
down_revision = 'd4946cc6c566'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admin', schema=None) as batch_op:
        batch_op.drop_column('champSpecifiqueAdmin')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admin', schema=None) as batch_op:
        batch_op.add_column(sa.Column('champSpecifiqueAdmin', mysql.VARCHAR(length=100), nullable=True))

    # ### end Alembic commands ###
