"""empty message

Revision ID: d4946cc6c566
Revises: 069e5a3a607e
Create Date: 2024-06-07 22:27:39.676655

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd4946cc6c566'
down_revision = '069e5a3a607e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin',
    sa.Column('adminId', sa.Integer(), nullable=False),
    sa.Column('champSpecifiqueAdmin', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['adminId'], ['utilisateur.utilisateurId'], ),
    sa.PrimaryKeyConstraint('adminId')
    )
    with op.batch_alter_table('garage', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'utilisateur', ['garageId'], ['utilisateurId'])

    with op.batch_alter_table('police', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'utilisateur', ['policeId'], ['utilisateurId'])

    with op.batch_alter_table('utilisateur', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.String(length=50), nullable=True))
        batch_op.alter_column('telephone',
               existing_type=mysql.VARCHAR(length=20),
               type_=sa.String(length=15),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('utilisateur', schema=None) as batch_op:
        batch_op.alter_column('telephone',
               existing_type=sa.String(length=15),
               type_=mysql.VARCHAR(length=20),
               existing_nullable=False)
        batch_op.drop_column('type')

    with op.batch_alter_table('police', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('garage', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    op.drop_table('admin')
    # ### end Alembic commands ###
